"""create carrier credentials table

Revision ID: 2bc5746479e6
Revises: 3fb1f82a4474
Create Date: 2026-07-25 23:57:03.089520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bc5746479e6'
down_revision: Union[str, Sequence[str], None] = '3fb1f82a4474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_credentials',
    sa.Column('carrier_account_id', sa.Uuid(), nullable=False),
    sa.Column('credential_key', sa.String(length=100), nullable=False),
    sa.Column('credential_value', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['carrier_account_id'], ['carrier_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrier_credentials')
    # ### end Alembic commands ###
